services:
  pae_app:
    build:
      context: .
      dockerfile: docker/dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Live code mounting
      - ./app:/app
    env_file:
      - .env