services:
  pae_app:
    build:
      context: .
      dockerfile: irc_app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Live code mounting
      - ./app:/prod/app
    env_file:
      - .env