services:
  pae_app:
    build:
      context: .
      dockerfile: docker/dockerfile
    ports:
      - "8050:8050"
      - "3016:3016"
    volumes:
      # Live code mounting
      - ./app:/prod/app
    env_file:
      - .env