FROM python:3.12-slim

# Set the working directory
WORKDIR /prod

# 1. Copy ONLY the requirements file first
COPY docker/requirements.txt /prod/requirements.txt

# 2. Install dependencies (This layer is now cached!)
RUN pip install --no-cache-dir -r requirements.txt

# 3. Now copy the rest of your application code
COPY . /prod

# main
EXPOSE 8050
# emulator
EXPOSE 3016 

# Run the application
# -u forces the python stdout to be unbuffered, great for seeing logs in real-time
CMD ["python", "-m", "app.main"]